[2025-05-27T12:19:28.533+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: register_best_model_from_mlflow.select_best_model_from_mlflow manual__2025-05-27T12:18:25.987714+00:00 [queued]>
[2025-05-27T12:19:28.540+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: register_best_model_from_mlflow.select_best_model_from_mlflow manual__2025-05-27T12:18:25.987714+00:00 [queued]>
[2025-05-27T12:19:28.540+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2025-05-27T12:19:28.548+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): select_best_model_from_mlflow> on 2025-05-27 12:18:25.987714+00:00
[2025-05-27T12:19:28.558+0000] {standard_task_runner.py:60} INFO - Started process 1735 to run task
[2025-05-27T12:19:28.567+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'register_best_model_from_mlflow', 'select_best_model_from_mlflow', 'manual__2025-05-27T12:18:25.987714+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/register_best_model_from_mlflow.py', '--cfg-path', '/tmp/tmpbnrujobl']
[2025-05-27T12:19:28.570+0000] {standard_task_runner.py:88} INFO - Job 50: Subtask select_best_model_from_mlflow
[2025-05-27T12:19:28.610+0000] {task_command.py:423} INFO - Running <TaskInstance: register_best_model_from_mlflow.select_best_model_from_mlflow manual__2025-05-27T12:18:25.987714+00:00 [running]> on host f0b48d92db9c
[2025-05-27T12:19:28.662+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='register_best_model_from_mlflow' AIRFLOW_CTX_TASK_ID='select_best_model_from_mlflow' AIRFLOW_CTX_EXECUTION_DATE='2025-05-27T12:18:25.987714+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-27T12:18:25.987714+00:00'
[2025-05-27T12:19:28.667+0000] {file_store.py:331} WARNING - Malformed experiment 'artifacts'. Detailed error Yaml file '/app/mlruns/artifacts/meta.yaml' does not exist.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/store/tracking/file_store.py", line 327, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/store/tracking/file_store.py", line 421, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/store/tracking/file_store.py", line 1367, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/store/tracking/file_store.py", line 1360, in _read_helper
    result = read_yaml(root, file_name)
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/utils/file_utils.py", line 309, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '/app/mlruns/artifacts/meta.yaml' does not exist.
[2025-05-27T12:19:28.747+0000] {logging_mixin.py:188} INFO - üèÜ –õ—É—á—à–∞—è –º–æ–¥–µ–ª—å: run_id=66aa1abfeeaa46358945ae4fabe3734d, f1_score=0.5530009078475759
[2025-05-27T12:19:28.771+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/register_best_model_from_mlflow.py", line 38, in select_best_model_from_mlflow
    downloaded_model_path = download_artifacts(
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/artifacts/__init__.py", line 73, in download_artifacts
    return artifact_repo.download_artifacts(artifact_path, dst_path=dst_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 91, in download_artifacts
    raise OSError(f"No such file or directory: '{local_artifact_path}'")
OSError: No such file or directory: '/app/mlruns/348878099909276459/66aa1abfeeaa46358945ae4fabe3734d/artifacts/model/model.pkl'
[2025-05-27T12:19:28.780+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=register_best_model_from_mlflow, task_id=select_best_model_from_mlflow, execution_date=20250527T121825, start_date=20250527T121928, end_date=20250527T121928
[2025-05-27T12:19:28.787+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 50 for task select_best_model_from_mlflow (No such file or directory: '/app/mlruns/348878099909276459/66aa1abfeeaa46358945ae4fabe3734d/artifacts/model/model.pkl'; 1735)
[2025-05-27T12:19:28.833+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-27T12:19:28.851+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
