[2025-05-28T09:18:42.756+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_ml_models.train_and_log_models manual__2025-05-28T09:17:33.441393+00:00 [queued]>
[2025-05-28T09:18:42.763+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_ml_models.train_and_log_models manual__2025-05-28T09:17:33.441393+00:00 [queued]>
[2025-05-28T09:18:42.763+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2025-05-28T09:18:42.775+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): train_and_log_models> on 2025-05-28 09:17:33.441393+00:00
[2025-05-28T09:18:42.781+0000] {standard_task_runner.py:60} INFO - Started process 12503 to run task
[2025-05-28T09:18:42.787+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'train_ml_models', 'train_and_log_models', 'manual__2025-05-28T09:17:33.441393+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/train_models.py', '--cfg-path', '/tmp/tmpv4g9lsk1']
[2025-05-28T09:18:42.789+0000] {standard_task_runner.py:88} INFO - Job 25: Subtask train_and_log_models
[2025-05-28T09:18:42.822+0000] {task_command.py:423} INFO - Running <TaskInstance: train_ml_models.train_and_log_models manual__2025-05-28T09:17:33.441393+00:00 [running]> on host bbc28cef36b5
[2025-05-28T09:18:42.936+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='train_ml_models' AIRFLOW_CTX_TASK_ID='train_and_log_models' AIRFLOW_CTX_EXECUTION_DATE='2025-05-28T09:17:33.441393+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-28T09:17:33.441393+00:00'
[2025-05-28T09:18:44.497+0000] {logging_mixin.py:188} INFO - üì¶ –í—ã–ø–æ–ª–Ω—è–µ–º dvc pull...
[2025-05-28T09:18:44.499+0000] {logging_mixin.py:188} INFO - STDOUT: Everything is up to date.
[2025-05-28T09:18:44.499+0000] {logging_mixin.py:188} INFO - STDERR: 
[2025-05-28T09:18:45.526+0000] {logging_mixin.py:188} INFO - üì¶ Logging to MLflow at: http://mlflow:5000
[2025-05-28T09:18:45.819+0000] {logging_mixin.py:188} WARNING - 2025/05/28 09:18:45 INFO mlflow.tracking._tracking_service.client: üèÉ View run LogisticRegression_l1_C_0.1 at: http://mlflow:5000/#/experiments/1/runs/c4839d3f9a7e441688c689d15f5610c4.
[2025-05-28T09:18:45.821+0000] {logging_mixin.py:188} WARNING - 2025/05/28 09:18:45 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow:5000/#/experiments/1.
[2025-05-28T09:18:45.838+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/train_models.py", line 85, in train_and_log_models
    mlflow.log_input(from_pandas(df, context="training", source=dataset_path))
TypeError: from_pandas() got an unexpected keyword argument 'context'
[2025-05-28T09:18:45.876+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=train_ml_models, task_id=train_and_log_models, execution_date=20250528T091733, start_date=20250528T091842, end_date=20250528T091845
[2025-05-28T09:18:45.893+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 25 for task train_and_log_models (from_pandas() got an unexpected keyword argument 'context'; 12503)
[2025-05-28T09:18:45.922+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-28T09:18:45.948+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
